# Generated by Django 5.2.6 on 2025-10-15 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='journalist',
        ),
        migrations.AddField(
            model_name='publisher',
            name='editor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'editor'}, related_name='editor_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='journalist',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='journalist_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
