# Generated by Django 5.2.6 on 2025-10-15 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_remove_publisher_editor_remove_publisher_journalist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='editor',
            new_name='editors',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='journalist',
            new_name='journalists',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscriptions_to_newsletters',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions_to_journalists',
            field=models.ManyToManyField(blank=True, related_name='journalist_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
