# Generated by Django 5.2.6 on 2025-10-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_article_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('review_articles', 'Can review articles'), ('approve_article', 'Can approve article')]},
        ),
    ]
