# Generated by Django 5.2.7 on 2025-10-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
